# Common configuration shared between all applications
configserver:
    name: Docker ECOS-Registry
    status: Connected to the ECOS-Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@ecos-registry:8761/eureka/
