
server:
  port: 8094

ecos-app:
  id: ecos-model
  version: 1.2.0
  name: ECOS Model

spring:
  datasource:
    url: jdbc:postgresql://localhost:5441/emodel
    username: emodel
    password:

ecos:
  idp:
    default-realm: ecos-app
  job:
    inactiveUsersDisabling:
      cron: '0 0 0/6 ? * *'
