---
server:
  port: 8094

ecos-app:
  id: ecos-model
  version: 1.2.0
  name: ECOS Model

spring:
  datasource:
    url: jdbc:postgresql://localhost:14523/ecos_model
    username: model
    password: modelpassword
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration
      - org.springframework.boot.autoconfigure.data.ldap.LdapDataAutoConfiguration
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
ecos:
  idp:
    default-realm: ecos-app
  job:
    inactiveUsersDisabling:
      cron: '0 0 0/6 ? * *'
    activityStartUserTask:
      cron: '0 */5 * * * *'
  webapp:
    task:
      executors:
        txn-actions:
          corePoolSize: 10
    x509:
      keys:
        application:
          location: classpath:ecos/x509/keys/application.key
    hazelcast:
      mapConfigs:
        personAuthorities:
          name: person-authorities-cache
          eviction:
            evictionPolicy: LRU
            size: 50
            maxSizePolicy: FREE_HEAP_SIZE
  integrations:
    onlyoffice:
      host: only-office-app
    keycloakAdmin:
      url: http://localhost/ecos-idp/auth
      user: admin
      password: admin
      enabled: false
