
server:
  port: 8094

ecos-app:
  id: ecos-model
  version: 1.2.0
  name: ECOS Model

spring:
  datasource:
    url: jdbc:postgresql://localhost:14523/ecos_model
    username: model
    password: modelpassword

ecos:
  idp:
    default-realm: ecos-app
  job:
    inactiveUsersDisabling:
      cron: '0 0 0/6 ? * *'
  webapp:
    dataSources:
      main:
        xa: true
