
server:
  port: 8094

ecos-app:
  id: ecos-model
  version: 1.2.0
  name: ECOS Model

ecos:
  webapp:
    dataSources:
      main:
        url: jdbc:postgresql://localhost:5441/emodel
        username: emodel
        password:
  idp:
    default-realm: ecos-app
  job:
    inactiveUsersDisabling:
      cron: '0 0 0/6 ? * *'
