
alfresco:
    ribbon:
        listOfServers: localhost:8080
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

eapps:
    ribbon:
        listOfServers: localhost:8089
        NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList

eapps-watcher:
  artifacts:
    enabled: true
    locations: './src/main/resources/eapps/artifacts'

