---
server:
  port: 8094

ecos-app:
  id: ecos-model
  version: 1.2.0
  name: ECOS Model

spring:
  datasource:
    url: jdbc:postgresql://localhost:14523/ecos_model
    username: model
    password: modelpassword
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration
      - org.springframework.boot.autoconfigure.data.ldap.LdapDataAutoConfiguration

ecos:
  idp:
    default-realm: ecos-app
    keycloakServerUrl: http://localhost/ecos-idp/auth
    keycloakAdminPassword: VeryStrongPassword
    keycloakDefaultUserPassword: 123
  job:
    inactiveUsersDisabling:
      cron: '0 0 0/6 ? * *'
  webapp:
    dataSources:
      main:
        xa: true

  integrations:
    onlyoffice:
      host: only-office-app
