version: '2'
services:
  emodel-postgresql:
    image: postgres:11.4
    # volumes:
    #     - ~/volumes/ecos/emodel/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=emodel
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
