---
id: default
name:
  ru: По умолчанию
  en: Default

visibility: PUBLIC

system: true

workspaceMembers:
  - id: default-administrators
    authority: emodel/authority-group@ECOS_ADMINISTRATORS
    memberRole: MANAGER
  - id: default-all-users
    authority: emodel/authority-group@EVERYONE
    memberRole: USER
