---
id: base
name: { ru: Базовый журнал, en: Base journal }

system: true

columns:

  - id: displayName
    name: { ru: Имя, en: Name }
    attribute: _disp
    type: text

  - id: modifier
    name: { ru: Кем изменен, en: Changed by }
    attribute: _modifier
    type: text

  - id: modified
    name: { ru: Когда изменен, en: Changed time }
    attribute: _modified
    type: datetime
