---
id: wiki-initial-page-content
value:
  title:
    ru: Добро пожаловать!
    en: Welcome!
  text:
    ru: <p><br></p><p dir="ltr"><span>Добро пожаловать в базу знаний!</span></p>
    en: <p><br></p><p dir="ltr"><span>Welcome to wiki!</span></p>
valueDef:
  formRef: uiserv/form@wiki-initial-page-content
  attributes:
    - id: title
      type: MLTEXT
    - id: text
      type: MLTEXT
